version: '3'

services:
  db:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
