version: '3'

services:
  db:
    image: mysql:8.0.21
    ports:
      - 3306:3306
    volumes:
      - ./mysql-init-files:/docker-entrypoint-initdb.d
      - mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: passwd
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: passwd
    security_opt:
      - label=disable

  adminer:
    image: adminer:4.7.7
    ports:
      - 8888:8080

  ubuntu:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile
    command: ["sleep", "infinity"]

volumes:
  mysql-data:
